#!/usr/bin/env bash
# JordyLab library scan script.
# Generated by the gamecatalog module's ScriptService. Do not edit by hand —
# modify the source template at jordylab-be/src/main/resources/scripts/jordylab-scan-template.sh
# and re-run the build.
#
# Usage:  jordylab-scan-<library>.sh [--path <root>]
#
# Effects:
#   * Performs the Keycloak Device Authorization Grant against ${KEYCLOAK_URL}
#     (realm=${REALM}, client_id=${CLIENT_ID}) and caches the access+refresh
#     tokens at ~/.config/jordylab/scan/token.json (mode 0600).
#   * Walks the selected library type (${LIBRARY_TYPE}) under the auto-detected
#     default path, or the path supplied via --path.
#   * Builds a JSON payload with the directory listing (and, for Steam, the
#     contents of every appmanifest_<appid>.acf under steamapps/).
#   * POSTs the payload to ${BACKEND_URL}${SCAN_ENDPOINT} with the bearer
#     token and prints the server's response.

set -euo pipefail

KEYCLOAK_URL='${KEYCLOAK_URL}'
REALM='${REALM}'
CLIENT_ID='${CLIENT_ID}'
BACKEND_URL='${BACKEND_URL}'
SCAN_ENDPOINT='${SCAN_ENDPOINT}'
LIBRARY_TYPE='${LIBRARY_TYPE}'

CACHE_DIR="$HOME/.config/jordylab/scan"
TOKEN_FILE="$CACHE_DIR/token.json"
PAYLOAD_FILE="$CACHE_DIR/payload.json"

log() { printf '\033[1;36m[jordylab]\033[0m %s\n' "$*" >&2; }
err() { printf '\033[1;31m[jordylab]\033[0m %s\n' "$*" >&2; }

# ---- preflight --------------------------------------------------------------

command -v curl >/dev/null 2>&1 || { err "curl is required"; exit 1; }
command -v jq >/dev/null 2>&1 || { err "jq is required"; exit 1; }

detect_hostname() {
  local host
  host=$(hostnamectl --static 2>/dev/null || hostname 2>/dev/null || uname -n 2>/dev/null || true)
  host=${host%%.*}
  if [ -z "$host" ]; then
    err "Could not determine the system hostname. Run 'hostnamectl set-hostname your-pc-name' and retry."
    exit 1
  fi
  echo "$host"
}

# ---- path detection ---------------------------------------------------------

default_path() {
  case "$LIBRARY_TYPE" in
    STEAM)
      # Steam library roots — newer and older Linux defaults
      for candidate in "$HOME/.local/share/Steam" "$HOME/.steam/steam" "$HOME/.steam" "$HOME/Steam"; do
        if [ -d "$candidate/steamapps" ]; then
          echo "$candidate"
          return 0
        fi
      done
      echo "$HOME/.local/share/Steam"  # best-effort default if Steam isn't installed yet
      ;;
    EMUDECK)
      if [ -d "$HOME/Emulation/roms" ]; then
        echo "$HOME/Emulation/roms"
      else
        echo "$HOME/Emulation/roms"
      fi
      ;;
  esac
}

SCAN_ROOT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --path) SCAN_ROOT="$2"; shift 2;;
    --help|-h)
      sed -n '2,15p' "$0"
      exit 0;;
    *) err "Unknown argument: $1"; exit 1;;
  esac
done

if [ -z "$SCAN_ROOT" ]; then
  SCAN_ROOT=$(default_path)
  log "No --path supplied; using default $SCAN_ROOT"
fi

if [ ! -d "$SCAN_ROOT" ]; then
  err "Path '$SCAN_ROOT' does not exist. Use --path to point at your library root."
  exit 1
fi

PC_NAME=$(detect_hostname)
log "Hostname: $PC_NAME"
log "Library type: $LIBRARY_TYPE"
log "Scan root: $SCAN_ROOT"

# ---- keycloak device-code flow ---------------------------------------------

mkdir -p "$CACHE_DIR"
chmod 0700 "$CACHE_DIR"

token_endpoint="$KEYCLOAK_URL/realms/$REALM/protocol/openid-connect/token"
device_endpoint="$KEYCLOAK_URL/realms/$REALM/protocol/openid-connect/auth/device"

request_device_code() {
  log "Requesting device code from $device_endpoint"
  local response
  response=$(curl --silent --show-error --fail-with-body --max-time 15 \
      -X POST "$device_endpoint" \
      -H "Content-Type: application/x-www-form-urlencoded" \
      --data-urlencode "client_id=$CLIENT_ID" \
      --data-urlencode "scope=openid")
  echo "$response"
}

poll_for_token() {
  local device_code="$1" interval="$2" expires_at="$3"
  while [ "$(date +%s)" -lt "$expires_at" ]; do
    sleep "$interval"
    local response
    response=$(curl --silent --max-time 15 -X POST "$token_endpoint" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:device_code" \
        --data-urlencode "client_id=$CLIENT_ID" \
        --data-urlencode "device_code=$device_code")
    if echo "$response" | jq -e '.access_token' >/dev/null 2>&1; then
      echo "$response"
      return 0
    fi
    local err
    err=$(echo "$response" | jq -r '.error // empty' 2>/dev/null || true)
    if [ "$err" = "authorization_pending" ]; then
      continue
    fi
    if [ "$err" = "slow_down" ]; then
      interval=$((interval + 5))
      continue
    fi
    if [ -n "$err" ]; then
      err "Device-code error: $err"
      return 1
    fi
  done
  err "Device code expired before user authorised."
  return 1
}

refresh_access_token() {
  local refresh="$1"
  curl --silent --show-error --fail-with-body --max-time 15 -X POST "$token_endpoint" \
      -H "Content-Type: application/x-www-form-urlencoded" \
      --data-urlencode "grant_type=refresh_token" \
      --data-urlencode "client_id=$CLIENT_ID" \
      --data-urlencode "refresh_token=$refresh"
}

ensure_token() {
  if [ -f "$TOKEN_FILE" ]; then
    local refresh
    refresh=$(jq -r '.refresh_token // empty' "$TOKEN_FILE" 2>/dev/null || true)
    if [ -n "$refresh" ] && [ "$refresh" != "null" ]; then
      log "Refreshing cached token"
      if refreshed=$(refresh_access_token "$refresh") && echo "$refreshed" | jq -e '.access_token' >/dev/null 2>&1; then
        echo "$refreshed" | jq '.expires_in |= . + 0' > "$TOKEN_FILE"
        chmod 0600 "$TOKEN_FILE"
        return 0
      fi
      err "Refresh failed; falling back to device-code flow"
    fi
  fi

  local device_response code verifier expires_at interval_now
  device_response=$(request_device_code)
  code=$(echo "$device_response" | jq -r '.device_code')
  verifier=$(echo "$device_response" | jq -r '.user_code')
  local verification_uri complete_uri expires_in interval
  verification_uri=$(echo "$device_response" | jq -r '.verification_uri')
  complete_uri=$(echo "$device_response" | jq -r '.verification_uri_complete // empty')
  expires_in=$(echo "$device_response" | jq -r '.expires_in')
  interval=$(echo "$device_response" | jq -r '.interval')

  if [ -z "$code" ] || [ "$code" = "null" ]; then
    err "Could not request device code: $device_response"
    exit 1
  fi

  if [ -n "$complete_uri" ] && [ "$complete_uri" != "null" ]; then
    log "Open this URL in any browser and enter the code:"
    log "  $complete_uri"
  else
    log "Open $verification_uri in any browser and enter code: $verifier"
  fi
  log "Waiting for authorisation…"

  interval=${interval:-5}
  if [ "$interval" -lt 5 ]; then interval=5; fi
  expires_at=$(( $(date +%s) + expires_in ))

  poll_for_token "$code" "$interval" "$expires_at" | tee "$TOKEN_FILE" >/dev/null
  chmod 0600 "$TOKEN_FILE"
}

ensure_token
ACCESS_TOKEN=$(jq -r '.access_token' "$TOKEN_FILE")
if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" = "null" ]; then
  err "Failed to obtain an access token"
  exit 1
fi

# ---- payload construction ---------------------------------------------------

CAPTURED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

list_steam() {
  log "Walking $SCAN_ROOT for Steam library"
  if [ ! -d "$SCAN_ROOT/steamapps" ]; then
    err "$SCAN_ROOT/steamapps does not exist. Is this really a Steam install?"
    exit 1
  fi
  local entries
  entries=$(cd "$SCAN_ROOT" && find steamapps -type f -printf '%p\t%s\t%TY-%Tm-%Td %TH:%TM:%TS\n' 2>/dev/null \
    | jq -R 'split("\t") | {relpath: .[0], size: (.[1] | tonumber), mtime: .[2]}')
  local manifests
  manifests=$(cd "$SCAN_ROOT" && find steamapps -name 'appmanifest_*.acf' -type f 2>/dev/null)
  local manifest_json
  manifest_json="{}"
  if [ -n "$manifests" ]; then
    while IFS= read -r manifest; do
      [ -z "$manifest" ] && continue
      local body
      body=$(cat "$manifest" | jq -Rs '.')
      manifest_json=$(echo "$manifest_json" | jq --arg key "$manifest" --argjson val "$body" '. + {($key): $val}')
    done <<< "$manifests"
  fi
  jq -n \
    --arg hostname "$PC_NAME" \
    --arg libraryType "STEAM" \
    --arg capturedAt "$CAPTURED_AT" \
    --argjson paths "$entries" \
    --argjson manifests "$manifest_json" \
    '{hostname: $hostname, libraryType: $libraryType, capturedAt: $capturedAt, paths: $paths, manifestContents: $manifests}'
}

list_emudeck() {
  log "Walking $SCAN_ROOT for EmuDeck library"
  local available
  available=$(find "$SCAN_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | sort)
  if [ -z "$available" ]; then
    err "No emulator subfolders found under $SCAN_ROOT"
    exit 1
  fi
  log "Detected emulator subfolders:"
  echo "$available" | sed 's/^/  - /' >&2
  log "Enter the subfolders to scan, space-separated (default: all):"
  local selected
  if read -r -t 30 selected; then
    :  # use user input
  else
    log "No input after 30s, scanning all subfolders"
    selected="$available"
  fi
  if [ -z "$selected" ]; then selected="$available"; fi
  local subfolders
  subfolders=$(echo "$selected" | tr ' ' '\n' | sed '/^$/d' | sort -u)

  local entries
  entries="[]"
  while IFS= read -r sub; do
    [ -z "$sub" ] && continue
    [ ! -d "$SCAN_ROOT/$sub" ] && continue
    local walked
    walked=$(cd "$SCAN_ROOT" && find "$sub" -type f -printf '%p\t%s\t%TY-%Tm-%Td %TH:%TM:%TS\n' 2>/dev/null \
      | jq -R 'split("\t") | {relpath: .[0], size: (.[1] | tonumber), mtime: .[2]}')
    entries=$(jq -n --argjson a "$entries" --argjson b "$walked" '$a + $b')
  done <<< "$subfolders"

  jq -n \
    --arg hostname "$PC_NAME" \
    --arg libraryType "EMUDECK" \
    --arg capturedAt "$CAPTURED_AT" \
    --argjson paths "$entries" \
    '{hostname: $hostname, libraryType: $libraryType, capturedAt: $capturedAt, paths: $paths, manifestContents: {}}'
}

case "$LIBRARY_TYPE" in
  STEAM)   list_steam   > "$PAYLOAD_FILE";;
  EMUDECK) list_emudeck > "$PAYLOAD_FILE";;
  *) err "Unknown library type: $LIBRARY_TYPE"; exit 1;;
esac

SUBMITTED=$(jq '.paths | length' "$PAYLOAD_FILE")
log "Built payload: $SUBMITTED file(s)"

# ---- submit ----------------------------------------------------------------

log "POSTing to $BACKEND_URL$SCAN_ENDPOINT"
http_status=$(curl --silent --show-error --max-time 60 -o "$CACHE_DIR/last-response.json" -w '%{http_code}' \
    -X POST "$BACKEND_URL$SCAN_ENDPOINT" \
    -H "Authorization: Bearer $ACCESS_TOKEN" \
    -H "Content-Type: application/json" \
    --data-binary "@$PAYLOAD_FILE")
log "HTTP $http_status"
cat "$CACHE_DIR/last-response.json" | jq . 2>/dev/null || cat "$CACHE_DIR/last-response.json"

case "$http_status" in
  200) exit 0;;
  401) err "Server rejected the token. Run with --help to inspect or delete $TOKEN_FILE to force re-auth."; exit 1;;
  403) err "Forbidden — your Keycloak user lacks the gamecatalog-scanner role."; exit 1;;
  *) exit 1;;
esac
