package dev.jordy.jordylab.gamecatalog.service;

import jakarta.annotation.PostConstruct;
import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import org.springframework.util.StreamUtils;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Renders and serves the resident Python scan client. The template is the frozen
 * artifact committed at {@code src/main/resources/scripts/jordylab-scan-template.py}
 * (generated by {@code gamecatalog-scanner/tools/build_client.py}). The generator
 * substitutes the {@code ${...}} placeholders in the template's constants header,
 * emitting each value as an escaped Python string literal.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ClientService {

    private static final String TEMPLATE_PATH = "scripts/jordylab-scan-template.py";

    @Value("${jordylab.script.keycloak-url:http://localhost:8180}")
    String keycloakUrl;

    @Value("${jordylab.script.realm:jordylab}")
    String realm;

    @Value("${jordylab.script.client-id:gamecatalog-script}")
    String clientId;

    private String scriptTemplate;

    @PostConstruct
    void init() {
        this.scriptTemplate = loadTemplate();
    }

    public String generateClient(String libraryType, HttpServletRequest httpRequest) {
        String normalized = libraryType == null ? "" : libraryType.trim().toLowerCase(Locale.ROOT);
        if (!normalized.equals("steam") && !normalized.equals("emudeck")) {
            throw new IllegalArgumentException("libraryType must be 'steam' or 'emudeck'");
        }

        Map<String, String> vars = new HashMap<>();
        vars.put("KEYCLOAK_URL", stripTrailingSlash(keycloakUrl));
        vars.put("REALM", realm);
        vars.put("CLIENT_ID", clientId);
        vars.put("BACKEND_URL", resolveBackendUrl(httpRequest));
        vars.put("LIBRARY_TYPE", normalized.toUpperCase(Locale.ROOT));
        vars.put("SCAN_ENDPOINT", "/api/gamecatalog/ingest/scan");

        return render(scriptTemplate, vars);
    }

    static String escapePythonString(String value) {
        StringBuilder escaped = new StringBuilder(value.length());
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\' -> escaped.append("\\\\");
                case '"' -> escaped.append("\\\"");
                case '\n' -> escaped.append("\\n");
                case '\r' -> escaped.append("\\r");
                case '\t' -> escaped.append("\\t");
                default -> escaped.append(character);
            }
        }

        return escaped.toString();
    }

    private static String stripTrailingSlash(String value) {
        if (!StringUtils.hasText(value)) {
            return "";
        }

        return value.endsWith("/") ? value.substring(0, value.length() - 1) : value;
    }

    private static String resolveBackendUrl(HttpServletRequest request) {
        if (request == null) {
            return "";
        }
        String forwardedScheme = request.getHeader("X-Forwarded-Proto");
        String scheme = StringUtils.hasText(forwardedScheme) ? forwardedScheme : request.getScheme();
        String host = request.getServerName();
        int port = request.getServerPort();
        boolean isDefaultPort = (scheme.equals("http") && port == 80) || (scheme.equals("https") && port == 443);

        StringBuilder url = new StringBuilder().append(scheme).append("://").append(host);
        if (!isDefaultPort) {
            url.append(':').append(port);
        }

        return url.toString();
    }

    private static String render(String template, Map<String, String> vars) {
        StringBuilder out = new StringBuilder(template.length());
        int cursor = 0;
        while (cursor < template.length()) {
            int match = template.indexOf("${", cursor);
            if (match < 0) {
                out.append(template, cursor, template.length());

                break;
            }
            out.append(template, cursor, match);
            int close = template.indexOf('}', match + 2);
            if (close < 0) {
                out.append(template, cursor, template.length());

                break;
            }
            String key = template.substring(match + 2, close);
            String value = vars.get(key);
            if (value == null) {
                out.append(template, match, close + 1);
            } else {
                out.append(escapePythonString(value));
            }
            cursor = close + 1;
        }

        return out.toString();
    }

    private static String loadTemplate() {
        try (InputStream input = new ClassPathResource(TEMPLATE_PATH).getInputStream()) {
            return StreamUtils.copyToString(input, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new IllegalStateException("Client template not found: " + TEMPLATE_PATH, exception);
        }
    }
}
